
package optimusinventorysystem;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JTable;
import optimusinventorysystem.bean.DBOperations;
import optimusinventorysystem.report.JasperReportGenerator;
import optimusinventorysystem.bean.UserPersonalDetailBean;
import java.io.InputStream;


 
public class UserPersonalReport extends javax.swing.JFrame {

    DBOperations objDB;
    ArrayList alstUser;

    /** Creates new form UserAccountReport */
    public UserPersonalReport() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        objDB = new DBOperations();
        alstUser=objDB.getAllUserPersonalDetailList();
        generateTable();
        setTitle("User Personal Detail Report");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    void generateTable() {


        Object data[][] = new Object[alstUser.size()][7];
        for (int i = 0; i < alstUser.size(); i++)
        {
            UserPersonalDetailBean objBean = (UserPersonalDetailBean) alstUser.get(i);
            data[i][0] = objBean.getUserId();
            data[i][1] = objBean.getName();
            data[i][2] = objBean.getDateOfBirth();
            data[i][3] = objBean.getAddress();
            data[i][4] = objBean.getMobile();
            data[i][5] = objBean.getPhone();
            data[i][6] = objBean.getEmail();

        }
        String header[] = {"User ID", "Name", "Date Of Birth", "Address", "Mobile", "Phone" ,"Email"};
        tblUserAccount = new JTable(data, header);
        jScrollPane1.setViewportView(tblUserAccount);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miPrint = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Date Of Birth", "Address", "Mobile", "Phone", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblUserAccount);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Personal Detail Report");

        jMenu1.setText("File");

        miPrint.setText("Print");
        miPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrintActionPerformed(evt);
            }
        });
        jMenu1.add(miPrint);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_miExitActionPerformed

    private void miPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrintActionPerformed
        // TODO add your handling code here:
        //String path = getClass().getResource("../optimusinventorysystem/report/UserPersonalReport.jrxml").getPath();
         InputStream st = getClass().getResourceAsStream("/optimusinventorysystem/report/UserPersonalReport.jrxml");
         JasperReportGenerator jrg=new JasperReportGenerator(st);
    }//GEN-LAST:event_miPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserPersonalReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miPrint;
    private javax.swing.JTable tblUserAccount;
    // End of variables declaration//GEN-END:variables
}
